package controller

import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.toComposeImageBitmap
import org.jetbrains.skia.Image
import utils.Constants.B
import utils.Constants.L
import utils.Constants.O
import utils.Constants.P
import utils.Constants.S
import utils.Constants.T
import java.io.File

class ImageLoader {

    val images = loadImages(
        listOf(
            "$B/BeamBlock01.png",
            "$B/BeamBlock02.png",
            "$B/BeamBlock03.png",
            "$B/BeamBlock04.png",
            "$B/BeamBlock05.png",
            "$B/BeamBlock06.png",
            "$B/BeamBlock07.png",
            "$B/BlackBlock01.png",
            "$B/BlackBlock02.png",
            "$B/BlackBlock03.png",
            "$B/BlackBlock04.png",
            "$B/BlackBlock05.png",
            "$B/BlackBlock06.png",
            "$B/BlackBlock07.png",
            "$B/BrickBlock01.png",
            "$B/BrickBlock02.png",
            "$B/BrickBlock03.png",
            "$B/BrickBlock04.png",
            "$B/BrickBlock05.png",
            "$B/BrickBlock06.png",
            "$B/BrickBlock07.png",
            "$B/ChequeredBlock01.png",
            "$B/ChequeredBlock02.png",
            "$B/ChequeredBlock03.png",
            "$B/ChequeredBlock04.png",
            "$B/ChequeredBlock05.png",
            "$B/ChequeredBlock06.png",
            "$B/ChequeredBlock07.png",
            "$B/ChequeredBlock08.png",
            "$B/ChequeredBlock09.png",
            "$B/ChequeredBlock10.png",
            "$B/ChequeredBlock11.png",
            "$B/ChequeredBlock12.png",
            "$B/ChequeredBlock13.png",
            "$B/ChequeredBlock14.png",
            "$B/ChippedBlock01.png",
            "$B/ChippedBlock02.png",
            "$B/ChippedBlock03.png",
            "$B/ChippedBlock04.png",
            "$B/ChippedBlock05.png",
            "$B/ChippedBlock06.png",
            "$B/CrossBlock01.png",
            "$B/CrossBlock02.png",
            "$B/CrossBlock03.png",
            "$B/CrossBlock04.png",
            "$B/CrossBlock05.png",
            "$B/CrossBlock06.png",
            "$B/CrossBlock07.png",
            "$B/CrossBlock08.png",
            "$B/CrossBlock09.png",
            "$B/CrossBlock10.png",
            "$B/CrossBlock11.png",
            "$B/CrossBlock12.png",
            "$B/CrossBlock13.png",
            "$B/CrossBlock14.png",
            "$B/CrossBlock15.png",
            "$B/DestructibleBlock01.png",
            "$B/GridBlock01.png",
            "$B/GridBlock02.png",
            "$B/GridBlock03.png",
            "$B/GridBlock04.png",
            "$B/GridBlock05.png",
            "$B/GridBlock06.png",
            "$B/GridBlock07.png",
            "$B/GridBlock08.png",
            "$B/PaneBlock01.png",
            "$B/PaneBlock02.png",
            "$B/PaneBlock03.png",
            "$B/PaneBlock04.png",
            "$B/PatternedBlock01.png",
            "$B/PatternedBlock02.png",
            "$B/PatternedBlock03.png",
            "$B/PatternedBlock04.png",
            "$B/PatternedBlock05.png",
            "$B/PatternedBlock06.png",
            "$B/PatternedBlock07.png",
            "$B/RegularBlock01.png",
            "$B/TileBlock01.png",
            "$B/TileBlock02.png",
            "$B/TileBlock03.png",
            "$B/TileBlock04.png",
            "$B/TileBlock05.png",
            "$B/TileBlock06.png",
            "$B/TileBlock07.png",
            "$O/MetallicPlatform01.png",
            "$O/MetallicPlatform02.png",
            "$O/MetallicPlatform03.png",
            "$O/MetallicPlatform04.png",
            "$O/MetallicPlatform05.png",
            "$O/MetallicPlatform06.png",
            "$O/MetallicPlatform07.png",
            "$O/MetallicPlatform08.png",
            "$O/MetallicPlatform09.png",
            "$O/MetallicPlatform10.png",
            "$O/PanePlatform01.png",
            "$O/PanePlatform02.png",
            "$O/PanePlatform03.png",
            "$O/PanePlatform04.png",
            "$O/PanePlatform05.png",
            "$O/PanePlatform06.png",
            "$O/PanePlatform07.png",
            "$O/PanePlatform08.png",
            "$O/PanePlatform09.png",
            "$O/RegularPlatform01.png",
            "$O/RegularPlatform02.png",
            "$O/RegularPlatform03.png",
            "$O/RegularPlatform04.png",
            "$O/RegularPlatform05.png",
            "$O/WavyPlatform01.png",
            "$O/WavyPlatform02.png",
            "$O/WavyPlatform03.png",
            "$O/WavyPlatform04.png",
            "$O/WavyPlatform05.png",
            "$O/WavyPlatform06.png",
            "$P/CurvedPit01.png",
            "$P/CurvedPit02.png",
            "$P/JaggedPit01.png",
            "$P/JaggedPit02.png",
            "$P/JaggedPit03.png",
            "$P/SerratedPit01.png",
            "$P/SerratedPit02.png",
            "$P/SerratedPit03.png",
            "$P/SerratedPit04.png",
            "$P/ThornPit01.png",
            "$P/ThornPit02.png",
            "$P/ThornPit03.png",
            "$P/ThornPit04.png",
            "$P/ThornPit05.png",
            "$P/ThornPit06.png",
            "$P/VinePit01.png",
            "$P/VinePit02.png",
            "$P/VinePit03.png",
            "$P/VinePit04.png",
            "$P/WavyPit01.png",
            "$P/WavyPit02.png",
            "$P/WavyPit03.png",
            "$P/WavyPit04.png",
            "$P/WavyPit05.png",
            "$P/WavyPit06.png",
            "$L/BlockOutline01.png",
            "$L/BlockOutline02.png",
            "$L/BlockOutline03.png",
            "$L/BlockOutline04.png",
            "$L/BlockOutline05.png",
            "$L/Cornerpiece01.png",
            "$L/Cornerpiece02.png",
            "$L/Cornerpiece03.png",
            "$L/Cornerpiece04.png",
            "$L/PlatformOutline01.png",
            "$L/PlatformOutline02.png",
            "$L/PlatformOutline03.png",
            "$L/PlatformOutline04.png",
            "$L/PlatformOutline05.png",
            "$L/PlatformOutline06.png",
            "$L/PlatformOutline07.png",
            "$L/PlatformOutline08.png",
            "$L/SlopeOutline01.png",
            "$L/SlopeOutline02.png",
            "$S/ColourSpike01.png",
            "$S/ColourSpike02.png",
            "$S/ColourSpike03.png",
            "$S/ColourSpike04.png",
            "$S/FakeSpike01.png",
            "$S/FakeSpike02.png",
            "$S/FakeSpike03.png",
            "$S/FakeSpike04.png",
            "$S/OutlineSpike01.png",
            "$S/OutlineSpike02.png",
            "$S/OutlineSpike03.png",
            "$S/RegularSpike01.png",
            "$S/RegularSpike02.png",
            "$S/RegularSpike03.png",
            "$S/RegularSpike04.png",
            "$T/BlackRing.png",
            "$T/CustomRing.png",
            "$T/CyanPad.png",
            "$T/CyanRing.png",
            "$T/GreenPointer.png",
            "$T/GreenRing.png",
            "$T/MagentaPad.png",
            "$T/MagentaPointer.png",
            "$T/MagentaRing.png",
            "$T/RedPad.png",
            "$T/RedRing.png",
            "$T/YellowPad.png",
            "$T/YellowRing.png"
        )
    )
    val indices = images.indices.toList()

    private fun loadImages(fileNames: List<String>): List<ImageBitmap> {
        return fileNames.map { Image.makeFromEncoded(File("src/main/resources/$it").readBytes()).toComposeImageBitmap() }
    }

}